CC = clang
CFLAGS = -O3 -flto -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Wundef -Wstrict-prototypes -Wmissing-prototypes -Wformat=2 -Wfloat-equal -Wcast-align -Wswitch-enum -Wvla -Werror
LDFLAGS = -O3 -flto

TARGET = app

SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET) $(LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

rebuild: clean all
